# Exersice-3 Linear algebra with numpy

In [2]:
import numpy as np

In [3]:
#1)Create 3X2 and 2X3 array.
arr1=np.array([[1,2],[3,4],[5,6]])
arr2=np.array([[1,2,3],[4,5,6]])

In [8]:
#2)Initialize the array with random values
arr1 = np.random.randint(6, size=(3,2))
arr2=np.random.randint(6, size=(2,3))

In [10]:
#3)matrix multiplication of above 2 array
print(arr1)
print(arr2)
ans=arr1.dot(arr2)
ans

[[0 1]
 [0 3]
 [5 2]]
[[1 2 3]
 [3 3 3]]


array([[ 3,  3,  3],
       [ 9,  9,  9],
       [11, 16, 21]])

In [11]:
#4)elementwise multiplication
arr3=np.array([[7,8],[9,10],[11,12]])
np.multiply(arr1,arr3)

array([[ 0,  8],
       [ 0, 30],
       [55, 24]])

In [12]:
#5)Find mean of a matrix
arr1.mean()

1.8333333333333333

In [19]:
#6) Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version
from numpy import genfromtxt
data = genfromtxt('mtcars.csv', delimiter=',')

In [20]:
data = np.delete(data,0, axis=0)
data = np.delete(data,0, axis=1)
data_mean_centric = data - np.mean(data, axis=0)
np.around(data_mean_centric, decimals=2)

array([[ 0.5],
       [-0.5]])

In [21]:
np.around(np.mean(data_mean_centric,axis=0),decimals=2)

array([0.])