In [50]:
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [51]:
#Reading CSV data
import pandas as pd
datasets = pd.read_csv('Dataset3.csv') 
print("\nData :\n",datasets)


Data :
    Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0


In [52]:
#Partitioning Data
X = datasets.iloc[:, :-1].values 
Y = datasets.iloc[:, -1].values 

print("\n\nInput : \n", X) 
print("\n\nOutput: \n", Y) 



Input : 
 [['R' 'H' 'F' 1]
 ['R' 'H' 'T' 2]
 ['O' 'H' 'F' 1]
 ['R' 'M' 'F' 1]
 ['S' 'C' 'F' 1]
 ['O' 'C' 'T' 0]
 ['O' 'C' 'T' 1]
 ['R' 'M' 'F' 1]
 ['O' 'C' 'F' 0]
 ['S' 'M' 'F' 2]
 ['R' 'C' 'T' 2]
 ['O' 'M' 'T' 0]
 ['O' 'H' 'F' 1]
 ['S' 'M' 'T' 1]]


Output: 
 [0 0 1 1 1 0 1 0 1 1 0 1 1 0]


In [53]:
#Label Encoding on all columns except last
le = LabelEncoder()
Outlook_encoded=le.fit_transform(X[ : ,0])
X[ : ,0]=Outlook_encoded
print(Outlook_encoded)

[1 1 0 1 2 0 0 1 0 2 1 0 0 2]


In [54]:
Temp_encoded=le.fit_transform(X[ : ,1])
X[ : ,1]=Temp_encoded
print(Temp_encoded)

[1 1 1 2 0 0 0 2 0 2 0 2 1 2]


In [55]:
Wind_encoded=le.fit_transform(X[ : ,2])
X[ : ,2]=Wind_encoded
print(Wind_encoded)

[0 1 0 0 0 1 1 0 0 0 1 1 0 1]


In [56]:
#Combining Features
features=tuple(zip(Outlook_encoded,Temp_encoded,Wind_encoded,X[ : ,3]))
print("Features:",features)

Features: ((1, 1, 0, 1), (1, 1, 1, 2), (0, 1, 0, 1), (1, 2, 0, 1), (2, 0, 0, 1), (0, 0, 1, 0), (0, 0, 1, 1), (1, 2, 0, 1), (0, 0, 0, 0), (2, 2, 0, 2), (1, 0, 1, 2), (0, 2, 1, 0), (0, 1, 0, 1), (2, 2, 1, 1))


In [57]:
model=MultinomialNB()
model.fit(features,Y)

MultinomialNB()

In [58]:
#What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?
predicted= model.predict([[1,2,0,1]]) #Rainy=1, Mild=2, False=0, Normal=1
print("Predicted Value:", predicted)

Predicted Value: [1]


In [59]:
#What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’, and Wind = ’True’?
predicted= model.predict([[2,0,1,2]]) #Sunny=2, Cool=0, True=1, High=2
print("Predicted Value:", predicted)

Predicted Value: [0]


In [60]:
#Finding accuracy 
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(X,
                        Y, test_size = 0.05, random_state = 137)

In [62]:
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [63]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 1.0


In [64]:
#Precision and Recall
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 1.0
recall: 1.0
